/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import etablissement.Etablissement;
import etablissement.person.Person;
import gui.principal.PrincipalPanel;
import gui.principal.classrooms.AddClassDialog;
import gui.principal.classrooms.AddStudentDialog;
import java.awt.CardLayout;

/**
 *
 * @author aroquemaurel
 */
public final class MainFrame extends javax.swing.JFrame {
    public static Etablissement etablissement;
    public static Person currentPerson;
    /**
     * Creates new form MainFrame
     * @param e l'établissement
     */
    public MainFrame(Etablissement e) {
        if(e == null) {
            etablissement = new Etablissement();
        } else {
            etablissement = e;
        }
        initComponents();
        hideMenuPrincipal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        connexionPanel1 = new gui.ConnexionPanel();
        principalFrame1 = new gui.principal.PrincipalPanel();
        teacherPanel1 = new gui.teachers.TeacherPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        actionDeconnexion = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        actionNewClass = new javax.swing.JMenuItem();
        actionAddStudent = new javax.swing.JMenuItem();
        actionAddTeacher = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new java.awt.CardLayout());
        jPanel1.add(connexionPanel1, "card2");
        jPanel1.add(principalFrame1, "card3");
        jPanel1.add(teacherPanel1, "card4");

        getContentPane().add(jPanel1, "card5");

        jMenu1.setText("Fichier");

        actionDeconnexion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/power_off.png"))); // NOI18N
        actionDeconnexion.setText("Se déconnecter");
        actionDeconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionDeconnexionActionPerformed(evt);
            }
        });
        jMenu1.add(actionDeconnexion);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/exit.png"))); // NOI18N
        jMenuItem5.setText("Fermer");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Classes");

        actionNewClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/add.png"))); // NOI18N
        actionNewClass.setText("Nouvelle classe");
        actionNewClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionNewClassActionPerformed(evt);
            }
        });
        jMenu2.add(actionNewClass);

        actionAddStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/add.png"))); // NOI18N
        actionAddStudent.setText("Nouvel élève");
        actionAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionAddStudentActionPerformed(evt);
            }
        });
        jMenu2.add(actionAddStudent);

        actionAddTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/add.png"))); // NOI18N
        actionAddTeacher.setText("Ajouter un enseignant");
        jMenu2.add(actionAddTeacher);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void actionDeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionDeconnexionActionPerformed
        ((CardLayout)(jPanel1.getLayout())).first(jPanel1);
    }//GEN-LAST:event_actionDeconnexionActionPerformed

    private void actionNewClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionNewClassActionPerformed
        (new AddClassDialog(this, true)).setVisible(true);
    }//GEN-LAST:event_actionNewClassActionPerformed

    private void actionAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionAddStudentActionPerformed
        (new AddStudentDialog(this, true)).setVisible(true);
    }//GEN-LAST:event_actionAddStudentActionPerformed

    public PrincipalPanel getPrincipalFrame1() {
        return principalFrame1;
    }

    public void launch() {
                /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem actionAddStudent;
    private javax.swing.JMenuItem actionAddTeacher;
    private javax.swing.JMenuItem actionDeconnexion;
    private javax.swing.JMenuItem actionNewClass;
    private gui.ConnexionPanel connexionPanel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private gui.principal.PrincipalPanel principalFrame1;
    private gui.teachers.TeacherPanel teacherPanel1;
    // End of variables declaration//GEN-END:variables

    public void showMenuPrincipal() {
        jMenu2.setVisible(true);
    }

    public void hideMenuPrincipal() {
        jMenu2.setVisible(false);
    }
}
