/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import etablissement.Etablissement;
import java.awt.CardLayout;

/**
 *
 * @author aroquemaurel
 */
public class MainFrame extends javax.swing.JFrame {

    public static Etablissement etablissement;
    /**
     * Creates new form MainFrame
     * @param e l'établissement
     */
    public MainFrame(Etablissement e) {
        etablissement = e;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        connexionPanel1 = new gui.ConnexionPanel();
        principalFrame1 = new gui.principal.PrincipalFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        actionDeconnexion = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        actionNewClass = new javax.swing.JMenuItem();
        actionAddStudent = new javax.swing.JMenuItem();
        actionAddTeacher = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new java.awt.CardLayout());
        jPanel1.add(connexionPanel1, "card2");
        jPanel1.add(principalFrame1, "card3");

        getContentPane().add(jPanel1, "card5");

        jMenu1.setText("Fichier");

        actionDeconnexion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/power_off.png"))); // NOI18N
        actionDeconnexion.setText("Se déconnecter");
        actionDeconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionDeconnexionActionPerformed(evt);
            }
        });
        jMenu1.add(actionDeconnexion);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/exit.png"))); // NOI18N
        jMenuItem5.setText("Fermer");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Classes");

        actionNewClass.setText("Nouvelle classe");
        jMenu2.add(actionNewClass);

        actionAddStudent.setText("Ajouter un élève");
        jMenu2.add(actionAddStudent);

        actionAddTeacher.setText("Ajouter un enseignant");
        jMenu2.add(actionAddTeacher);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Professeurs");

        jMenuItem4.setText("Ajouter un professeur");
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void actionDeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionDeconnexionActionPerformed
        ((CardLayout)(jPanel1.getLayout())).first(jPanel1);
        
    }//GEN-LAST:event_actionDeconnexionActionPerformed

    public void launch() {
                /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem actionAddStudent;
    private javax.swing.JMenuItem actionAddTeacher;
    private javax.swing.JMenuItem actionDeconnexion;
    private javax.swing.JMenuItem actionNewClass;
    private gui.ConnexionPanel connexionPanel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private gui.principal.PrincipalFrame principalFrame1;
    // End of variables declaration//GEN-END:variables
}
