/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui.principal;

import gui.MainFrame;
import gui.models.TeachersTableModel;

/**
 *
 * @author aroquemaurel
 */
public class TeachersPanel extends javax.swing.JPanel {
    /**
     * Creates new form TeachersPanel
     */
    public TeachersPanel() {
        initComponents();
        tableTeachers.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableTeachers = new javax.swing.JTable();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        tableTeachers.setModel(new TeachersTableModel(MainFrame.etablissement.getTeachers()));
        jScrollPane1.setViewportView(tableTeachers);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableTeachers;
    // End of variables declaration//GEN-END:variables
}
