/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui.principal.classrooms;

import etablissement.classroom.Classroom;
import etablissement.classroom.Level;
import gui.MainFrame;
import java.util.Set;
import etablissement.person.Teacher;
import gui.Utils;

/**
 *
 * @author aroquemaurel
 */
public class AddClassDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddClassFrame
     * @param parent
     * @param modal
     */
    public AddClassDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fillTeachers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 20));
        jLabel1 = new javax.swing.JLabel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 20));
        jPanel3 = new javax.swing.JPanel();
        level = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 20));
        jLabel2 = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jPanel6 = new javax.swing.JPanel();
        principalTeacher = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jButton1 = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setModal(true);
        setResizable(false);

        jPanel1.setLayout(new java.awt.GridLayout(3, 2));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));
        jPanel2.add(filler3);

        jLabel1.setText("Niveau");
        jPanel2.add(jLabel1);
        jPanel2.add(filler8);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        level.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sixième", "Cinquième", "Quatrième", "Troisième" }));
        level.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanel3.add(level);

        jPanel1.add(jPanel3);

        jPanel4.setMaximumSize(new java.awt.Dimension(32838, 20));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));
        jPanel4.add(filler4);

        jLabel2.setText("Professeur principal");
        jPanel4.add(jLabel2);
        jPanel4.add(filler7);

        jPanel1.add(jPanel4);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        principalTeacher.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanel6.add(principalTeacher);

        jPanel1.add(jPanel6);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));
        jPanel5.add(filler1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/add.png"))); // NOI18N
        jButton1.setText("Ajouter la classe");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jPanel5.add(filler2);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/cancel.png"))); // NOI18N
        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);

        getContentPane().add(jPanel5, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Set<Classroom> classrooms = MainFrame.etablissement.getClasses();
        Level l = new Level((String) level.getSelectedItem());
        Classroom newClass = new Classroom(l, MainFrame.etablissement.getNbClassLevel(l));
        Teacher headTeach = MainFrame.etablissement.getTeacherById(principalTeacher.getSelectedIndex());
        
        newClass.addTeacher(headTeach);
        newClass.setHeadTeacher(headTeach);
        classrooms.add(newClass);
        
        Utils.fillDataTreeClass(MainFrame.etablissement.getClasses(), 
                ((MainFrame)(getParent())).getPrincipalFrame1().getClassPanel1().getTreeClass());
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JComboBox level;
    private javax.swing.JComboBox principalTeacher;
    // End of variables declaration//GEN-END:variables

    private void fillTeachers() {
        for(Teacher t : MainFrame.etablissement.getTeachers()) {
            principalTeacher.addItem(t);
        }
    }
}
