/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui.principal.classrooms;

import etablissement.classroom.Classroom;
import gui.MainFrame;
import gui.Utils;
import gui.data.renderer.TeacherTableRenderer;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author aroquemaurel
 */
public final class ClassPanel extends javax.swing.JPanel {
    /**
     * Creates new form ClassPanel
     */
    public ClassPanel() {
        initComponents();
        
        if(MainFrame.etablissement != null) {
            Utils.fillDataTreeClass(MainFrame.etablissement.getClasses(), treeClass);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        treeClass = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listStudents = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        listTeachers = new javax.swing.JList();

        setLayout(new java.awt.BorderLayout());

        treeClass.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                treeClassValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(treeClass);

        add(jScrollPane1, java.awt.BorderLayout.WEST);

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        listStudents.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(listStudents);

        jPanel1.add(jScrollPane2);

        listTeachers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(listTeachers);

        jPanel1.add(jScrollPane3);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    public void updateClassroom() {
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) treeClass.getLastSelectedPathComponent();
        if (node == null) {   //Nothing is selected.  
            return;
        }
        Object nodeInfo = node.getUserObject();
        
        if (node.isLeaf()) {
            listStudents.setVisible(true);
            listTeachers.setVisible(true);
            Classroom c = MainFrame.etablissement.getClass(new Classroom((String)nodeInfo));
            listStudents.setListData(c.getStudents().toArray());
            listTeachers.setListData(c.getTeachers().toArray());
        } else {
            listStudents.setVisible(false);
            listTeachers.setVisible(false);
        }
    }
    private void treeClassValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_treeClassValueChanged
        updateClassroom();
    }//GEN-LAST:event_treeClassValueChanged

    public JTree getTreeClass() {
        return treeClass;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listStudents;
    private javax.swing.JList listTeachers;
    private javax.swing.JTree treeClass;
    // End of variables declaration//GEN-END:variables
}
